+level 1 challenges
clipklop/django_views_challenges pull request #1
Opened 2023-09-10 10:10 UTC by clipklop

2023-09-11 01:10 UTC, vppuzakov requested changes
👍 хорошая работа.
💡 5е упражнение надо доработать в рамках этого ПР

2023-09-11 01:10 UTC, vppuzakov commented on django_views_routing_homework/urls.py
> +    path('bye/', bye_user_view),
👍 прописали соответствие на url и вьюху

2023-09-11 01:10 UTC, vppuzakov commented on django_views_routing_homework/urls.py
> +    path('user-info/<int:user_id>/', get_user_info_view),
👍 добавили path параметр и его тип

2023-09-11 01:10 UTC, vppuzakov commented on django_views_routing_homework/views/level_1/a_welcome_user.py
> +    welcome_message = 'Hi, user'
👍

2023-09-11 01:10 UTC, vppuzakov commented on django_views_routing_homework/views/level_1/c_baned_username.py
> +   if username in BANNED_USERNAMES:
👍

2023-09-11 01:10 UTC, vppuzakov commented on django_views_routing_homework/views/level_1/e_month_title.py
> +    month_mapper = {
👍 словарь хорошо использовать для подобных задач
💡 давай его вынесем в константы, чтобы не создавать каждый раз на вызов функции

2023-09-11 01:10 UTC, vppuzakov commented on django_views_routing_homework/views/level_1/e_month_title.py
> +        return
💡 `return None` обязательно

2023-09-11 01:10 UTC, vppuzakov commented on django_views_routing_homework/views/level_1/e_month_title.py
> +        return JsonResponse(data=month_mapper[month_number], safe=False)
💡 эта функция не вьюха, поэтому не должна возвращать никакой `Response`, должна вернуть строку - кстати пропиши это в аннотацию к этой функции

2023-09-11 01:10 UTC, vppuzakov commented on django_views_routing_homework/views/level_1/e_month_title.py
> +    if get_month_title_by_number(month_number):
💡 дважды вызываем функцию - она дважды делает работу - следует сложить в переменную и уже работать с ней

2023-09-11 01:10 UTC, vppuzakov commented on django_views_routing_homework/views/level_1/e_month_title.py
> +    if month_number in month_mapper:
💡 можно не проверять и потом доставать значение из словаря - сделать это в один заход с помощью метода словаря `get`:

```python
month_name = month_mapper.get(month_number)
```

Посмотри что этот метод возвращает в случае, когда число не найдено

2023-09-12 10:02 UTC, clipklop commented on django_views_routing_homework/views/level_1/e_month_title.py
> +    if month_number in month_mapper:
Исправил в рамках нового коммита https://github.com/clipklop/django_views_challenges/pull/1/commits/32ba50d519690e7332f3dc689e6e6b0bba69f300

2023-09-12 10:03 UTC, clipklop commented
Исправил в рамках нового коммита https://github.com/clipklop/django_views_challenges/commit/32ba50d519690e7332f3dc689e6e6b0bba69f300

2023-09-19 21:35 UTC, merged